### ISSUE TITLE
Requires ImageMagick 7 

### ISSUE THREAD

**Issue by klimburg** [nforrester/downlinx#2]
Documentation should specify since 6->7 was a breaking change to the commandline entrypoint.

https://legacy.imagemagick.org/script/command-line-processing.php
vs 
https://imagemagick.org/script/command-line-processing.php

6.9 is the latest available deb 
https://launchpad.net/ubuntu/focal/+source/imagemagick

**Comment by nforrester** [comment]
Thank you! As an Arch user I was not aware of this.
