### ISSUE TITLE
Doesnt work on XFCE

### ISSUE THREAD

**Issue by klimburg** [nforrester/downlinx#4]
Not unexpected but opening a ticket to track.

This might just be an issue with my setup but what I'm seeing is the `xconf-query` set is not overriding what i have in `xfdesktop`

**Comment by nforrester** [comment]
I got that command line from a Stack Exchange post from 2013. Maybe it's out of date. https://askubuntu.com/a/380615

There are other suggestions further down the thread. Perhaps one of those will help.

**Comment by klimburg** [comment]
Ok looks like i needed to use `/backdrop/screen0/monitorHDMI-0/workspace0/last-image` instead of `/backdrop/screen0/monitor0/image-path` for setting. 
```
$ xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitorHDMI-0/workspace0/last-image --set /home/kevin/Code/downlinx/pipelines/simple/images/generated5.png
```

**Comment by klimburg** [comment]
I'll put up a PR later for this

**Comment by nforrester** [comment]
Thank you for fixing `set_background_xfce()`. I merged your PR.
